
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - automators.labs.nibz.science
  resources:
  - factorioservers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - automators.labs.nibz.science
  resources:
  - factorioservers/status
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
