apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: minio
  name: factorio-backing-store
  labels:
    billingType: hourly
    region: us-west
    zone: sjc04
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 24Gi
  storageClassName: ibmc-file-silver
